#services:
#  client:
#    build:
#      context: ./client
#    ports:
#      - "8080:80"
#    depends_on:
#      - server
#      - db
#    networks:
#      - app-network
#
#  server:
#    build:
#      context: ./server
#      args:
#        - NODE_ENV=${NODE_ENV}
#        - DATABASE_URL=${DATABASE_URL}
#        - PORT=${PORT}
#        - JWT_SECRET=${JWT_SECRET}
#        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
#        - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
#        - FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
#        - FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}
#    ports:
#      - "${PORT}:${PORT}"
#    depends_on:
#      - db
#    networks:
#      - app-network
#
#  db:
#    image: mongo:4.2
#    volumes:
#      - ./db/data:/data/db
#    ports:
#      - "27017:27017"
#    networks:
#      - app-network
#
#networks:
#  app-network:
#    driver: bridge


services:
  server:
    build: ./server
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env

  client:
    build: ./client
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - server

